blank_issues_enabled: false
contact_links:
  - name: CNCF Slack (#serverless-workflow)
    url: https://slack.cncf.io/
    about: Join the CNCF Slack workspace and visit #serverless-workflow for real-time support.